/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_lwindow1 (void);
GtkWidget* create_lwindow2 (void);
GtkWidget* create_lwindow3 (void);
GtkWidget* create_lwindow5 (void);
GtkWidget* create_lwindow6 (void);
GtkWidget* create_lwindow7 (void);
GtkWidget* create_lwindow8 (void);
GtkWidget* create_lwindow9 (void);
GtkWidget* create_lwindow10 (void);
GtkWidget* create_lwindow11 (void);
GtkWidget* create_lwindow12 (void);
